module.exports = {
  ACTION_TYPES: {
    SET_ACTIVE_SLIDE: "SET_ACTIVE_SLIDE",
    SET_CELIA_VERTICAL_POSITION: "SET_CELIA_VERTICAL_POSITION",
    SET_ANIMATION_FRAME: "SET_ANIMATION_FRAME",
    SET_CELIA_VERTICAL_DIRECTION: "SET_CELIA_VERTICAL_DIRECTION",
    SET_ANIMATION_MAX_HEIGHT: "SET_ANIMATION_MAX_HEIGHT",
    SET_IS_MOBILE: "SET_IS_MOBILE"
  }
}
